INSERT INTO BOOKING_RESTAURANT.RESTAURANT(NAME,DESCRIPTION,ADDRESS,IMAGE) VALUES ("McDonald's","Fast Food","1 Nte. 1272, Talca","https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Fquetalquita%2Fstatus%2F1366812949453692941&psig=AOvVaw0yUwJ6m8cQHc-dDbuimNk7&ust=1645718699303000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCODbgJ2alvYCFQAAAAAdAAAAABAD");
INSERT INTO BOOKING_RESTAURANT.RESTAURANT(NAME,DESCRIPTION,ADDRESS,IMAGE) VALUES ("Burger King","Fast Food","Mall de Curico, Curico","https://www.google.com/url?sa=i&url=https%3A%2F%2Fm.facebook.com%2FBurger-king-curico-106969617609882%2F&psig=AOvVaw2GXaVOkC00TtfXcliIx3BF&ust=1645718798570000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCNCEsrealvYCFQAAAAAdAAAAABAP");
INSERT INTO BOOKING_RESTAURANT.RESTAURANT(NAME,DESCRIPTION,ADDRESS,IMAGE) VALUES ("Subway's Talca 2","Sandwiches Food","1 Nte 1272, Talca","https://www.google.com/url?sa=i&url=https%3A%2F%2Fmimapa.cl%2Flisting%2Fsubway-talca-2%2F&psig=AOvVaw1xSYOQbXL1NLbwue2uCtxb&ust=1645718944634000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCPDoyfualvYCFQAAAAAdAAAAABAD");

INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("MAÑANA",1);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("TARDE",1);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("NOCHE",1);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("TARDE",2);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("NOCHE",2);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("MAÑANA",3);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("TARDE",3);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("NOCHE",3);
INSERT INTO BOOKING_RESTAURANT.TURN(NAME,RESTAURANT_ID) VALUES("TRASNOCHE",3);

INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(7,1,1);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(1,2,1);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(6,3,1);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(3,1,2);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(4,2,2);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(12,1,3);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(6,2,3);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(2,3,3);
INSERT INTO BOOKING_RESTAURANT.BOARD(CAPACITY,NUMBER,RESTAURANT_ID) VALUES(3,4,3);